default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sat-db_development

test:
  <<: *default
  database: sat-db_test

production:
  <<: *default
  database: sat-db_production
  host: localhost